//
// Author : Vincenzo Gulizzi (LBL)
// Contact: vgulizzi@lbl.gov
//
/** \file AMReX_DG_Solution_Parabolic.H
 * \brief Contains functions for implicit-mesh discontinuous Galerkin methods for parabolic PDEs.
*/

#ifndef AMREX_DG_SOLUTION_PARABOLIC_H_
#define AMREX_DG_SOLUTION_PARABOLIC_H_

#include <AMReX_Geometry.H>
#include <AMReX_MFIter.H>
#include <AMReX_MultiFab.H>

#include <AMReX_DG_Constants.H>
#include <AMReX_DG_StandardElement.H>
#include <AMReX_DG_ImplicitMesh.H>
#include <AMReX_DG_MatrixFactory.H>

namespace amrex
{
namespace DG
{
namespace Parabolic
{

namespace Explicit
{


} // namespace Explicit

} // namespace Parabolic
} // namespace DG
} // namespace amrex

#endif