//
// Author : Vincenzo Gulizzi (LBL)
// Contact: vgulizzi@lbl.gov
//
/** \file AMReX_dG_Solution_Utils.H
 * \brief Functions to manipulate dG solutions.
*/

#ifndef AMREX_DG_SOLUTION_UTILS_H_
#define AMREX_DG_SOLUTION_UTILS_H_

#include <AMReX_VTK_Utils.H>

#include <AMReX_dG_Solution.H>

namespace amrex
{
namespace dG
{
namespace solution_utils
{

} // namespace solution_utils
} // namespace dG
} // namespace amrex

#endif