//
// Author : Vincenzo Gulizzi (LBL)
// Contact: vgulizzi@lbl.gov
//
/** \file AMReX_DG_IBVP.H
 * \brief Contains constants and data structures for Initial-Boundary Value problems.
*/

#ifndef AMREX_DG_IBVP_H_
#define AMREX_DG_IBVP_H_

namespace amrex
{
namespace DG
{

/**
 * \brief Base Initial-Boundary Value problem class.
 *
*/
struct IBVP_BASE
{
};


} // namespace DG
} // namespace amrex

#endif